### PR TITLE
support http dependency range ">=0.13.6 <2.0.0"

### PR DESCRIPTION
**Pull request by asaarnak**

### CODE REVIEW

**Comment by HatsuneMikuV** [comment]
I need this upgrade, is it possible

**Comment by natebgurutech** [comment]
I also need this upgrade, having serious dependency conflicts with the old version of http

**Comment by jupiterchan123** [comment]
please fix this

**Comment by juanfactor88** [comment]
Hi, please update the http dependency, Im also having issues with this.

**Comment by asaarnak** [comment]
@sf-tyler-jeong @OnestarLee
Could you check this please?

**Comment by sf-tyler-jeong** [comment]
Hi! @asaarnak 
To upgrade the http package version to 1.0.0 or higher, we must upgrade the dart version to 3.0 or higher.
We can't upgrade the dart version easily because we need to make as few breaking changes as possible for our customers.

Could it be possible to use the desired http package version using the `dependency_overrides` below?
`dependency_overrides:`
`  http: ^1.1.0`

We will update the dart version and other package versions at the appropriate time.
If there are critical issues in `http 0.13.6`, please let me know.
Thanks!

**Comment by asaarnak** [comment]
Hi! @sf-tyler-jeong 
Thanks for a reply.

`dependency_overrides` suggestion works for us, but it's a workaround we would like to remove.

Dart 3 is required by Flutter 3.10.0 that was released May 5 2023, it`s 6 months ago.

Developers usually use latest stable flutter or they will have problems with other dependencies that have required to update to Dart 3. For example `url_launcher` dependency has required Dart 3.0 for 5 months.

And its possible to support dependency range like `package_info_plus` does with `http` to not introduce new major version:
image

**Comment by asaarnak** [comment]
Also dependency loses pub points in pub.dev because of outdated dependencies.
image

**Comment by sf-tyler-jeong** [comment]
@asaarnak 
Thank you for all the information!!

**Comment by asaarnak** [comment]
Even flutter.dev updates to Dart 3 by minor version upgrade. Should be ok if there are no runtime breaking changes.
image

**Comment by asaarnak** [comment]
@sf-tyler-jeong Any news on this PR?

**Comment by asaarnak** [comment]
@sf-tyler-jeong Ping.

**Comment by martinberger12** [comment]
Devs stop wasting time around and upgrade this package.

**Comment by asaarnak** [comment]
@sf-tyler-jeong Any updates?

**Comment by sf-tyler-jeong** [comment]
Hi, @asaarnak 
Because there are customers who continue to use previous Flutter versions, it is not possible to easily upgrade Flutter and Dart versions. As far as I know, there is no problem because there is an alternative as mentioned above. Please let me know if you have any other issues related to this issue in your project.

**Comment by asaarnak** [comment]
This PR is not breaking. It supports both versions.

**Comment by sf-tyler-jeong** [comment]
@asaarnak
Sorry, I misunderstood about it.
I will update sdk regarding this when next release if there is no issue.
Thanks!

**Comment by sf-tyler-jeong** [comment]
Done!

**Comment by sf-tyler-jeong** [comment]
Done! Thanks!

**Pull request closed without merging**
