### PR TITLE
fix: deprecated hasValues

### PR DESCRIPTION
**Pull request by Kiruel**
Change for `Object.hash`.

### CODE REVIEW

**Comment by Kiruel** [comment]
Hi @danieljiwonkang98 , can you take look please ? I can't mock the `BaseMessage` because of this. I just test my patch and my tests pass now with this change.

Thanks.

**Comment by danieljiwonkang98** [comment]
Hello @Kiruel, thank you for the comment. Will take a look and update. Will leave a comment on this thread when update has been made.

**Comment by Kiruel** [comment]
Thanks ! Have a nice day.

**Comment by danieljiwonkang98** [comment]
Fix has been released in V `3.2.11`. Have a nice day!

**Pull request closed without merging**
