### PR TITLE
fix: mixin inherits from not object

### PR DESCRIPTION
**Pull request by Kiruel**
What I suggest is to use `with` and not `extends` for `GroupChannelHandler` and `OpenChannelHandler`.

Because of this https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=mixin_inherits_from_not_object#mixin_inherits_from_not_object

We can't use `with` for `GroupChannelHandler`. This PR fix this.

My typical controller to handle sendbird:
```
@Riverpod(keepAlive: false)
class ThreadController extends _$ThreadController with BaseChannelHandler, GroupChannelHandler  {
```

### CODE REVIEW

**Comment by sf-tyler-jeong** [comment]
Hi @Kiruel.

Is there any issue to implement with this handler class using extends below?

`class MyGroupChannelHandler extends GroupChannelHandler {}`

Thanks!

**Comment by Kiruel** [comment]
Yes because I already `extends _$ThreadController` so I can't use two extends. Like the V3 I should perform with to use the method. And choose what abstract classe I want to use.

I'm currently migrate the V3 to V4 and they are many thinks to do. Can you re-activate issues on the repos too ? I think it's better to make an issue then create the PRs if needed thanks.

**Comment by sf-tyler-jeong** [comment]
@Kiruel 
We are sorry for your inconvenience related to migration from v3 to v4.
But I think there are alternatives regarding this issue.
And It is difficult to modify our structure/architecture we decided for v4.

We have to disable the issue tab to follow our policy.
But you can make an issue on https://community.sendbird.com/.

Thanks!

**Comment by Kiruel** [comment]
Thanks for your reply, what alternatives do you propose ?

Because today I can't do this:

```dart
@riverpod
class MyController extends _$MyController with GroupChannelHandler {
```

Screenshot 2023-06-30 at 11 14 56

**Comment by Kiruel** [comment]
Maybe we could just change the `abstract class GroupChannelHandler extends BaseChannelHandler {` to `mixin class GroupChannelHandler extends BaseChannelHandler {` same for `OpenChannelHandler` and `FeedChannelHandler`.

Like propose here:
https://github.com/dart-lang/sdk/issues/48167

**Comment by sf-tyler-jeong** [comment]
@Kiruel
We will discuss this issue.
Thanks!

**Comment by Kiruel** [comment]
My solution [here](https://github.com/sendbird/sendbird-chat-sdk-flutter/pull/70#issuecomment-1614379249) do not work properly, I find a way to "mute" the warning. But I think something can be done to make it better.

```yaml
analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
```

**Comment by Kiruel** [comment]
Even with that I still got error on compilation:

```
my_controller.dart:22:10: Error: The class 'GroupChannelHandler' can't be used as a mixin because it extends a class other than 'Object'.
    with GroupChannelHandler {
         ^
         ```
I will wait for another version to make the migration. In current state it's impossible to migrate.

**Comment by sf-tyler-jeong** [comment]
@Kiruel
I think this code can be an alternative below.

In order to support `with` instead of `extends`,
1. We may delete `BaseChannelHandler` like v3. (not good)
2. Or we may select this way `with BaseChannelHandler, GroupChannelHandler` you've commented above. (not good)
3. And these changes will make breaking changes. (not good)

So I recommend the alternative to you.

`
class _$MyController {}

class MyController extends _$MyController {
  late MyGroupChannelHandler handler;

  MyController() {
    handler = MyGroupChannelHandler(controller: this);
  }

  void refresh() {}
}

class MyGroupChannelHandler extends GroupChannelHandler {
  final MyController controller;

  MyGroupChannelHandler({required this.controller});

  @override
  void onMessageReceived(BaseChannel channel, BaseMessage message) {
    controller.refresh();
  }
}
`

**Pull request closed without merging**
